# Convert RGB to greyscale
rgb_to_greyscale.py: 
  working_dir: .
  image_dir: <DIR_PATH>
  output_dir: <DIR_PATH>
  bands: 1


# Convert tiff to geotiff
tiff2geotiff.py: 
  image_dir: /data/images/run99/


# Standardize image color to a reference image
match_colour.py: 
  working_dir: .
  image_dir: <DIR_PATH>
  output_dir: <DIR_PATH>
  reference: <PATH_TO_REF_IMAGE>
  method: scikit   # 1: scikit, 2: rasterio
  plot: False


clip.py:
  working_dir: .
  aoi_shapefile: <AOI_SHPFILE_PATH>
  detections_dir: <DIR_PATH>
  output_dir: output/


mosaic.py:  
  working_dir: .
  input_dir: <DIR_PATH>
  output_dir: <DIR_PATH>


gt_analysis.py:
  working_dir: ./data/ground_truth/
  labels: 20240916_GT_CH.gpkg