# 
clip.py:
  working_dir: /mnt/c/Users/Clemence/Documents/git/STDL/proj-sda/
  aoi_shapefile: input/limiti_cantone_2012_shp_MN95/limiti_cantone_2012_MN95.shp
  detections_shapefile: input/dqry_detections/
  output_dir: output/