# 
clip.py:
  working_dir: .
  aoi_shapefile: input/limiti_cantone_2012_shp_MN95/limiti_cantone_2012_MN95.shp
  detections_shapefile: input/dqry_detections/
  output_dir: output/

# Track object in different datasets over years
track_detections.py:  
  working_dir: .
  years: [1999, 2001, 2003, 2004, 2005, 2006, 2009, 2012, 2015, 2018, 2021]                         
  detections_shapefile: output/dqry_detections_tessin.gpkg 
  output_dir: output/

# Plots
plots.py:  
  working_dir: .
  plots: ['area-year'] 
  object_id: [1, 4, 43, 66]   
  detections_shapefile: output/detections_years.gpkg  
  output_dir: output/plots