# 1-Produce tile geometries based on the AoI extent and zoom level
prepare_data.py:  
  srs: EPSG:2056
  datasets:
    shapefile: ./data/ground_truth/20240805_GT_MT_MES.gpkg                  
    category: 'Classe'
  output_folder: ./output/OD/det/zoom16/run58/
  zoom_level: 16 


# 2-Fetch of tiles (online server) and split into 3 datasets: train, test, validation
generate_tilesets.py:
  debug_mode: 
    enable: False  # sample of tiles
    nb_tiles_max: 10
  working_directory: .
  datasets:
    aoi_tiles: output/OD/det/zoom16/run58/tiles.geojson
    ground_truth_labels: output/OD/det/zoom16/run58/labels.geojson
    # FP_labels: output/OD/det/FP.geojson
    image_source:
      # ############ 
      type: XYZ                             # supported values: 1. MIL = Map Image Layer 2. WMS 3. XYZ 4. FOLDER
      year: multi-year                   # supported values: 1. multi-year (tiles of different year), 2. <year> (i.e. 2020)
      location: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage-product/default/{year}/3857/{z}/{x}/{y}.jpeg
      # ############ 
  output_folder: output/OD/det/zoom16/run58/
  tile_size: 256      # per side, in pixels
  overwrite: True
  n_jobs: 10
  seed: 2
  COCO_metadata:
    year: 2024
    version: 1.0
    description: Anthropogenic soils (Ticino, Vaud and swissTML3D 2024)
    contributor: swisstopo
    url: https://swisstopo.ch
    license:
      name: Unknown
      url:


# Object detection with the optimised trained model
make_detections.py:
  working_directory: ./output/OD/det/zoom16/run58
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files:           # relative paths, w/ respect to the working_folder
    trn: COCO_trn.json
    val: COCO_val.json
    tst: COCO_tst.json
  detectron2_config_file: ../../../../../config/detectron2_config.yaml # path relative to the working_folder
  model_weights:
    pth_file: ./logs/model_0002999.pth # trained model minimising the validation loss curve, monitor the training process via tensorboard (tensorboard --logdir </logs>)
  image_metadata_json: img_metadata.json
  rdp_simplification:   # rdp = Ramer-Douglas-Peucker
    enabled: true
    epsilon: 2.0        # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.05
  remove_det_overlap: True


# Assess the final results
merge_detections.py:
  working_dir: ./output/OD/det/zoom16/run53/
  labels: labels.geojson
  detections: tagged_detections.gpkg
  distance: 10 # m, distance use as a buffer to merge close polygons (likely to belong to the same object) together
  iou_threshold: 0.1
  score_threshold: 0.1
  assess: False
  

# 4-Filtering and merging detection polygons to improve final results
filter_results.py:
  detections: ./output/OD/det/zoom16/run53/tagged_detections_merged.gpkg
  zones_exclues:
    vaud: 
      pistes_avion: ./data/layers/Vaud/Pistes_aviation_MO_CSDUR.shp
      batiments: ./data/layers/Vaud/Batiments_en_surface_MO.shp
    ticino:
      batiments_batir: ./data/layers/Ticino/Zones_batir_Ind.shp
  zones_infos:
    vaud: 
      sites_pollues: ./data/layers/Vaud/Sites_pollues_VD2022.shp
      sda: ./data/layers/Vaud/SDA_v5_2.shp
      slope: ./data/layers/Vaud/terrain_pente_VD.gpkg
    ticino:
      sda: ./data/layers/Ticino/Censimento_SAC_2023.shp
      slope: ./data/layers/Ticino/terrain_pente_TC.gpkg
  dem: ./data/DEM/switzerland_dem_EPSG2056.tif
  elevation: 600.0 # m, altitude threshold
  slope: 100 # deg, slope threshold
  score: 0.1 # detection score (from 0 to 1) provided by detectron2
  area: 50.0 # m2, area threshold under which polygons are discarded