# Convert RGB to greyscale
rgb_to_greyscale.py: 
  working_dir: .
  image_dir: <DIR_PATH>
  output_dir: <DIR_PATH>
  bands: 1


# Convert tiff to geotiff
tiff2geotiff.py: 
  geotiff_image_dir: <DIR_PATH>
  tiff_image_dir: <DIR_PATH>


# Standardize image color to a reference image
match_colour.py: 
  working_dir: .
  image_dir: <DIR_PATH>
  output_dir: <DIR_PATH>
  reference: <PATH_TO_REF_IMAGE>
  method: rasterio   # 1: scikit, 2: rasterio
  plot: False


# Clip vectors
clip.py:
  working_dir: .
  aoi_shapefile: <AOI_SHPFILE_PATH>
  detections_dir: <DIR_PATH>
  output_dir: output/


# Mosaic raster
mosaic.py:  
  working_dir: .
  input_dir: <DIR_PATH>
  output_dir: <DIR_PATH>


# Plot year distribution of GT labels
gt_analysis.py:
  working_dir: <DIR_PATH>
  labels: <FILENAME>
  min_year: 1950
  max_year: 2025