# Produce tile geometries based on the AoI extent and zoom level
prepare_data.py:  
  srs: EPSG:2056
  datasets:
    shapefile: ./data/AoI/Ticino/Secteur_test_TC_v2.gpkg               
  output_folder: ./output/OD/det/ticino/
  zoom_level: 16 


# Fetch of tiles (online server) and split into 3 datasets: train, test, validation
generate_tilesets.py:
  debug_mode: 
    enable: False  # sample of tiles
    nb_tiles_max: 500
  working_directory: .
  datasets:
    aoi_tiles: ./output/OD/det/ticino/test/2020/tiles.geojson
    image_source:
      # ############ 
      type: XYZ                             # supported values: 1. MIL = Map Image Layer 2. WMS 3. XYZ 4. FOLDER
      year: 2020                  # supported values: 1. multi-year (tiles of different year), 2. <year> (i.e. 2020)
      location: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage-product/default/{year}/3857/{z}/{x}/{y}.jpeg
      # ############ 
  output_folder: ./output/OD/det/ticino/test/2020/
  tile_size: 256      # per side, in pixels
  overwrite: True
  n_jobs: 10
  seed: 2
  COCO_metadata:
    year: 2024
    version: 1.0
    description: Anthropogenic soils (Ticino, Vaud and swissTML3D 2024)
    contributor: swisstopo
    url: https://swisstopo.ch
    license:
      name: unknown
      url: unknown
    categories_file: ./output/OD/trne/zoom16/run66/category_ids.json


# Object detection with the optimised trained model
make_detections.py:
  working_directory: ./output/OD/det/ticino/test/2020/
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files:           # relative paths, w/ respect to the working_folder
    oth: COCO_oth.json
  detectron2_config_file: ../../../../../../config/detectron2_config.yaml # path relative to the working_folder
  model_weights:
    pth_file: ../../../../trne/zoom16/run66/logs/model_0002999.pth # trained model minimising the validation loss curve, monitor the training process via tensorboard (tensorboard --logdir </logs>)
  image_metadata_json: img_metadata.json
  rdp_simplification:   # rdp = Ramer-Douglas-Peucker
    enabled: true
    epsilon: 2.0        # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.05
  remove_det_overlap: True


# Assess the final results
merge_detections.py:
  working_dir: ./output/OD/det/ticino/test/2020/
  detections:
    oth: oth_detections_at_0dot05_threshold.gpkg
  distance: 10 # m, distance use as a buffer to merge close polygons (likely to belong to the same object) together
  iou_threshold: 0.1
  score_threshold: 0.05
  assess: False
  

# Filtering and merging detection polygons to improve final results
filter_results.py:
  working_dir: ./data
  detections: ../output/OD/det/ticino/test/AoI_v1/2020/inference_detections_merged.gpkg
  aoi: ./AoI/Ticino/Secteur_test_TC.gpkg
  canton: ticino
  infos:
    vaud: 
      landing_strip: ./layers/Vaud/Pistes_aviation_MO_CSDUR.shp
      batiments: ./layers/Vaud/Batiments_en_surface_MO.shp
      batiments_batir: ./layers/Vaud/Affectation_Zone_a_batir.gpkg
      sites_pollues: ./layers/Vaud/Sites_pollues_VD2022.shp
      sda: ./layers/Vaud/SDA_v5_2.shp
      slope: ./layers/Vaud/terrain_pente_VD.gpkg
    ticino:
      agri_area: ./layers/Ticino/Idoneità_Agricola.shp
      batiments_batir: ./layers/Ticino/Zones_batir_Ind.shp
      compa_SDA: ./layers/Ticino/Compatibilita_LPN-SAC_20241010.gpkg
      forests: ./layers/Ticino/Fôrets.shp
      grands_cours_eau: ./layers/Ticino/Grandi_corsi.shp
      protected_area: ./layers/Ticino/Compatibilita_LPN-SAC_20241010.gpkg
      protected_underground_water: ./layers/Ticino/Protezione_acque_sott.shp
      sites_pollues: ./layers/Ticino/Siti_inquinati.shp
      sda: ./layers/Ticino/Censimento_SAC_2023.shp
      slope: ./layers/Ticino/terrain_pente_TC_SA.gpkg
  exclusion: [batiments_batir, forests] 
  dem: ./DEM/switzerland_dem_EPSG2056.tif
  elevation_threshold: 900.0 # m, altitude threshold
  score_threshold: 0.05 # detection score (from 0 to 1) provided by detectron2
  area_threshold: 100.0 # m2, area threshold under which polygons are discarded


merge_years.py:
  canton: ticino
  working_dir: ./output/OD/det/{canton}/
  years: [2020, 2024]
  layer: inference_detections_merged_threshold_score-0dot1_area-50_elevation-600_overlap-0.gpkg 
