# 1-Produce tiles geometry according to the AoI extent and zoom level
prepare_data.py: 
  datasets:
    shapefile: ./data/AoI/Ticino/limiti_cantone_2012_MN95.shp
  output_folder: ./output/OD/detections/z16/run05
  zoom_level: 16  # z, keep between 15 and 18  
  srs: "EPSG:2056"  # Projection of the input file 

# 2-Request tiles according to the provided AOI and tiles parameters
generate_tilesets.py:
  debug_mode: 
    enable: True  # sample of tiles
    nb_tiles_max: 500
  working_directory: .
  datasets:
    aoi_tiles: output/OD/detections/z16/run05/tiles.geojson
    image_source:
      # type: FOLDER
      # location: data/images/SWISSIMAGE/zoom_16/RGB_det/2020/
      # srs: 3857
      type: XYZ                             # supported values: 1. MIL = Map Image Layer 2. WMS 3. XYZ 4. FOLDER
      year: 2020                     # supported values: 1. multi-year (tiles of different year), 2. <year> (i.e. 2020)
      location: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage-product/default/{year}/3857/{z}/{x}/{y}.jpeg
  output_folder: output/OD/detections/z16/run05/
  tile_size: 256 # per side, in pixels
  overwrite: False
  n_jobs: 10
  COCO_metadata:
    year: 2021
    version: 1.0
    description: Swiss Image Hinterground w/ Quarries and Mineral Exploitation Sites detection
    contributor: swisstopo
    url: https://swisstopo.ch
    license:
      name: Unknown
      url:

# 
rgb_to_greyscale.py: 
  working_dir: .
  image_dir: ./data/images/SWISSIMAGE/zoom_16/RGB_det/
  output_dir: ./data/images/SWISSIMAGE/zoom_16/Greyscale_det/1977


# 3-Object detection by inference with the optimised trained model
make_detections.py:
  working_directory: ./output/OD/detections/z16/run05
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files:           # relative paths, w/ respect to the working_folder
    oth: COCO_oth.json
  detectron2_config_file: ../../../../../config/detectron2_config.yaml # path relative to the working_folder
  model_weights:
    pth_file: ../../../trne/zoom16/run05/logs/model_0001999.pth # trained model minimising the validation loss curve, monitor the training process via tensorboard (tensorboard --logdir </logs>) 
  image_metadata_json: img_metadata.json
  rdp_simplification:   # rdp = Ramer-Douglas-Peucker
    enabled: True
    epsilon: 2.0        # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.05

# 4-Filtering and merging detection polygons to improve results
filter_detections.py:
  year: 1977
  detections: ./output/OD/detections/zoom_16/Greyscale_model/1977/oth_detections_at_0dot3_threshold.gpkg
  shapefile: ./data/limiti_cantone_2012_shp_MN95/limiti_cantone_2012_MN95.shp
  dem: ./data/DEM/switzerland_dem_EPSG2056.tif
  elevation: 1200.0   # m, altitude threshold
  score: 0.95         # detection score (from 0 to 1) provided by detectron2
  distance: 10        # m, distance use as a buffer to merge close polygons (likely to belong to the same object) together
  area: 5000.0        # m2, area threshold under which polygons are discarded
  output: ./output/OD/detections/zoom_16/Greyscale_model/1977/oth_detections_at_0dot3_threshold_year-{year}_score-{score}_area-{area}_elevation-{elevation}_distance-{distance}.geojson

# 
clip.py:
  working_dir: .
  aoi_shapefile: input/limiti_cantone_2012_shp_MN95/limiti_cantone_2012_MN95.shp
  detections_shapefile: input/dqry_detections/
  output_dir: output/

# Track object in different datasets over years
track_detections.py:  
  working_dir: .
  years: [1999, 2001, 2003, 2004, 2005, 2006, 2009, 2012, 2015, 2018, 2021]                         
  detections_shapefile: output/dqry_detections_tessin.gpkg 
  output_dir: output/

# Plots
plots.py:  
  working_dir: .
  plots: ['area-year'] 
  object_id: [1, 4, 43, 66]   
  detections_shapefile: output/detections_years.gpkg  
  output_dir: output/plots