# Prepare the AoI
prepare_aoi.py:  
  working_directory: data/AoI/
  canton: ticino
  year: 2022
  srs: EPSG:2056
  canton_shp: ./{canton}/<CANTON_SHPFILE>
  img_footprint_shp: ./swissimage_footprints/swissimage_footprint_{year}.shp     

# Produce tile geometries based on the AoI extent and zoom level
prepare_data.py:  
  datasets:
    shapefile: ./data/AoI/ticino/<AOI_SHPFILE>             
  output_folder: ./output/det/ticino/
  zoom_level: 16 

# Fetch of tiles (online server) and split into 3 datasets: train, test, validation
generate_tilesets.py:
  debug_mode: 
    enable: False  # sample of tiles
    nb_tiles_max: 2000
  working_directory: .
  datasets:
    aoi_tiles: ./output/det/ticino/tiles.geojson
    image_source:
      type: XYZ                             # supported values: 1. MIL = Map Image Layer 2. WMS 3. XYZ 4. FOLDER
      year: 2022                  # supported values: 1. multi-year (tiles of different year), 2. <year> (i.e. 2020)
      location: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage-product/default/{year}/3857/{z}/{x}/{y}.jpeg
  output_folder: ./output/det/ticino/
  tile_size: 256      # per side, in pixels
  overwrite: True
  n_jobs: 10
  seed: 2
  COCO_metadata:
    year: 2024
    version: 1.0
    description: Anthropogenic soils
    contributor: Ticino and Vaud
    url: 
    license:
      name: unknown
      url: unknown
    categories_file: data/category_ids.json

# Object detection with the optimised trained model
make_detections.py:
  working_directory: ./output/det/ticino/
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files:           # relative paths, w/ respect to the working_folder
    oth: COCO_oth.json
  detectron2_config_file: ../../../config/detectron2_config.yaml # path relative to the working_folder
  model_weights:
    pth_file: ../../../models/model_0002999.pth # trained model minimising the validation loss curve, monitor the training process via tensorboard (tensorboard --logdir </logs>)
  image_metadata_json: img_metadata.json
  rdp_simplification:   # rdp = Ramer-Douglas-Peucker
    enabled: True
    epsilon: 2.0        # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.05
  remove_det_overlap: True  # if several detections overlap (IoU > 0.5), only the one with the highest confidence score is retained

# Assess the final results
merge_detections.py:
  working_directory: ./output/det/ticino/
  detections:
    oth: oth_detections_at_0dot05_threshold.gpkg
  distance: 10 # m, distance use as a buffer to merge close polygons (likely to belong to the same object) together
  iou_threshold: 0.1
  score_threshold: 0.05
  assess: 
    enable: False
    metrics_method: micro-average   # 1: macro-average ; 2: macro-weighted-average ; 3: micro-average
  
# Filtering and merging detection polygons to improve final results
filter_detections.py:
  working_directory: ./data
  detections: ../output/det/ticino/merged_detections_at_0dot05_threshold.gpkg
  aoi: ./AoI/ticino/<AOI_SHPFILE>
  canton: ticino
  infos:
    layers_dir: layers/{canton}/
    ticino:
      agri_area: Idoneità_Agricola.shp
      building_areas: Zones_batir_Ind.shp
      climatic_areas: zones_climatiques_compatibles_sda_tc.gpkg
      compatible_SDA: Compatibilita_LPN-SAC_20241010.gpkg
      forests: Fôrets.shp
      large_rivers: Grandi_corsi.shp
      protected_underground_water: Protezione_acque_sott.shp
      polluted_sites: Siti_inquinati.shp
      sda: Censimento_SAC_2023.shp
      slope: terrain_pente_TC_SA.gpkg
      waters: MU_Acque_TI.shp
      zone_compatible_LPN: Zona_SAC_compatibile_con_i_disposti_LPN.gpkg
      zone_compatible_LPN_extensive: Zona_SAC_compatibile_con_i_disposti_LPN_previa_gestione_estensiva.gpkg
      zone_non_compatible_LPN: Zona_SAC_non_compatibile_con_i_disposti_LPN.gpkg
    vaud: 
      buildings: Batiments_en_surface_MO.gpkg
      building_areas: affectation_zone_a_batir.gpkg
      climatic_areas: zones_climatiques_compatibles_sda_VD.gpkg
      polluted_sites: Sites_pollues_VD2022.gpkg
      sda: SDA_v5_2.gpkg
      slope: terrain_pente_VD.gpkg
      waters: lakes_VD.gpkg
  attribute_names: layers/attribute_names.xlsx
  exclusion: [building_areas, forests, zone_non_compatible_LPN, waters] 
  dem: DEM/switzerland_dem_EPSG2056.tif
  elevation_threshold: 900.0 # m, altitude threshold
  score_threshold: 0.05 # detection score (from 0 to 1) provided by detectron2
  area_threshold: 100.0 # m2, area threshold under which polygons are discarded

merge_years.py:
  canton: <CANTON>
  working_directory: ./output/det/{canton}/
  years: [YEAR1, YEAR2, YEAR3]          # choose year
  layer: merged_detections_at_0dot05_threshold_threshold_score-0dot05_area-100_elevation-900.gpkg 
  overwrite: True
  file: concatenate   # supported values: 1. layers, 2. concatenate